package com.rp.dedup.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val PrimaryBlue = Color(0xFF0056D2)
val DarkBlue = Color(0xFF003896)
val LightBlueBadge = Color(0xFF00B2FF).copy(alpha = 0.1f)
val PrimaryRecordText = Color(0xFF00B2FF)
val DuplicateBadge = Color(0xFFF5F5F5)
val DuplicateText = Color(0xFF9E9E9E)
val TextDark = Color(0xFF1A1C1E)
val TextSecondary = Color(0xFF44474E)
val CardBackground = Color(0xFFF8F9FF)
val SelectionBarBackground = Color(0xFF2E3032)
val LightCyan = Color(0xFF80DEEA)
val DarkCyan = Color(0xFF00838F)
val ReclaimedBadge = Color(0xFF8DA9D4)
val DashboardCardBlue = Color(0xFF0047AB)
val ProgressTrack = Color(0xFFE0E0E0)
val PhotosColor = Color(0xFF4285F4)
val VideosColor = Color(0xFF34A853)
val DocumentsColor = Color(0xFF1967D2)
val RedBadge = Color(0xFFFFEBEE)
val RedText = Color(0xFFD32F2F)
val KeepBadgeBg = Color(0xFFB2EBF2)
val KeepBadgeText = Color(0xFF0097A7)

// ── Midnight (Indigo / Deep Purple) ───────────────────────────────────────
val MidnightPrimary       = Color(0xFF7C4DFF)
val MidnightPrimaryLight  = Color(0xFF5C35CC)
val MidnightSecondary     = Color(0xFFBB86FC)
val MidnightTertiary      = Color(0xFFCF6679)
val MidnightDarkBg        = Color(0xFF0D0D1A)
val MidnightDarkSurface   = Color(0xFF161628)
val MidnightDarkVariant   = Color(0xFF1F1F3D)
val MidnightLightBg       = Color(0xFFF3F0FF)
val MidnightLightVariant  = Color(0xFFEDE8FF)

// ── Forest (Deep Green) ───────────────────────────────────────────────────
val ForestPrimary         = Color(0xFF2E7D32)
val ForestPrimaryDark     = Color(0xFF4CAF50)
val ForestSecondary       = Color(0xFF388E3C)
val ForestTertiary        = Color(0xFF689F38)
val ForestDarkBg          = Color(0xFF0A140A)
val ForestDarkSurface     = Color(0xFF111E11)
val ForestDarkVariant     = Color(0xFF1A2D1A)
val ForestLightBg         = Color(0xFFF1F8E9)
val ForestLightVariant    = Color(0xFFE8F5E9)

// ── Sunset (Deep Orange / Amber) ──────────────────────────────────────────
val SunsetPrimary         = Color(0xFFE65100)
val SunsetPrimaryDark     = Color(0xFFFF6D00)
val SunsetSecondary       = Color(0xFFEF6C00)
val SunsetTertiary        = Color(0xFFF57F17)
val SunsetDarkBg          = Color(0xFF1A0800)
val SunsetDarkSurface     = Color(0xFF261200)
val SunsetDarkVariant     = Color(0xFF3D1A00)
val SunsetLightBg         = Color(0xFFFFF8F0)
val SunsetLightVariant    = Color(0xFFFFF3E0)

// ── Rose (Deep Pink / Mauve) ──────────────────────────────────────────────
val RosePrimary           = Color(0xFFAD1457)
val RosePrimaryDark       = Color(0xFFE91E8C)
val RoseSecondary         = Color(0xFFC2185B)
val RoseTertiary          = Color(0xFFE91E63)
val RoseDarkBg            = Color(0xFF1A0010)
val RoseDarkSurface       = Color(0xFF280020)
val RoseDarkVariant       = Color(0xFF3D0030)
val RoseLightBg           = Color(0xFFFFF0F5)
val RoseLightVariant      = Color(0xFFFCE4EC)

// ── Monochrome ────────────────────────────────────────────────────────────
val MonoPrimary           = Color(0xFF424242)
val MonoPrimaryDark       = Color(0xFFBDBDBD)
val MonoSecondary         = Color(0xFF616161)
val MonoTertiary          = Color(0xFF757575)
val MonoDarkBg            = Color(0xFF0A0A0A)
val MonoDarkSurface       = Color(0xFF141414)
val MonoDarkVariant       = Color(0xFF1F1F1F)
val MonoLightBg           = Color(0xFFFAFAFA)
val MonoLightVariant      = Color(0xFFF5F5F5)
